include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_single_quotes
    - sized_box_for_whitespace
    - sort_child_properties_last
    - unawaited_futures
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.gr.dart
  errors:
    unused_import: error
    always_declare_return_types: error
    annotate_overrides: error
    dead_code: error
    sort_constructors_first: error
