// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW1O69mfTjCWml2_LfHlofNPumi2JCOOI',
    appId: '1:280946449511:web:3d43b989c49336f57108c2',
    messagingSenderId: '280946449511',
    projectId: 'petbro-7287b',
    authDomain: 'petbro-7287b.firebaseapp.com',
    databaseURL: 'https://petbro-7287b.firebaseio.com',
    storageBucket: 'petbro-7287b.appspot.com',
    measurementId: 'G-67T85YS94H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAWUTknndAMQTQDxRrH-nyoQrF5Z4pUzs',
    appId: '1:280946449511:android:01822d3494dcb2d37108c2',
    messagingSenderId: '280946449511',
    projectId: 'petbro-7287b',
    databaseURL: 'https://petbro-7287b.firebaseio.com',
    storageBucket: 'petbro-7287b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDku7Ha6prFTaIdoXUjd1y4ig1qh8Pr9ow',
    appId: '1:280946449511:ios:52d63fbdd2e86d907108c2',
    messagingSenderId: '280946449511',
    projectId: 'petbro-7287b',
    databaseURL: 'https://petbro-7287b.firebaseio.com',
    storageBucket: 'petbro-7287b.appspot.com',
    iosClientId: '280946449511-vjson5gsnrlmr3o2anel0p9qag0pkml9.apps.googleusercontent.com',
    iosBundleId: 'com.example.petBro',
  );
}
